/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Controller.ControllerQuery;

/**
 *
 * @author Sofía Rubie García 117520883
 * @author Donald Cordoba Campos 304950089
 * @author Kyara Ávalos Escobar 402340732
 * @author Ali Pitti Gózalez 402450140
 *
 */

/* Module2
Está clase se encarga se inicia para que la cocina, en donde se tiene el boton para las órdenes, de este proceso, se brinda la opción de continuar interactuando con la aplicación.
Los botones que contiene son backorder list,detail of a particular order,
orderprocessing, report of processed orders y back.
 */
 /*BackOrder
Está es una de las clases del paquete vista, mismo que se encarga de  trabajar con el paquete modulo y
con el paquete control, en donde al momento en el que el usuario solicita BackOrder List, muestra las órdenes con 
su respectivo id, nombre del cashier, clientName, status, detail de la orden y el monto de dicha orden.
 */
 /*
Detail
Muestra el detalle de las órdenes, con respecto a la información de
cada uno de los datos que tiene la clase, el id de la factura, el cashier, clientName, status, detail y el cost total de cada orden.
 */
 /*Processing
Procesa y obtiene las órdenes, las puede visualizar en la cocina, con la finalidad de conviar de estado o definirlo por los encargados 
 */
 /*Report
Esta clase se encarga de mostrar el reporte de todas las órdenes procesadas por  la cafetería.
 */
public class InfoView extends javax.swing.JFrame {

    ControllerQuery controller;
    /**
     * Creates new form InvoiceView
     */
    ImagenFondo5 fondoBeve = new ImagenFondo5();

    public InfoView() {
        this.setContentPane(fondoBeve);
        initComponents();
        this.setExtendedState(6);
        this.controller = new ControllerQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroMostrar = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        Pendientes = new javax.swing.JButton();
        Particular = new javax.swing.JButton();
        Process = new javax.swing.JButton();
        IdLabel = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cuadroMostrar.setColumns(20);
        cuadroMostrar.setRows(5);
        jScrollPane1.setViewportView(cuadroMostrar);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Back_2.PNG"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Reporte.PNG"))); // NOI18N
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });

        Pendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Pendiente.PNG"))); // NOI18N
        Pendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendientesActionPerformed(evt);
            }
        });

        Particular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Detalle2.PNG"))); // NOI18N
        Particular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParticularActionPerformed(evt);
            }
        });

        Process.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Procesar.PNG"))); // NOI18N
        Process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessActionPerformed(evt);
            }
        });

        IdLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        IdLabel.setForeground(new java.awt.Color(255, 255, 204));
        IdLabel.setText("ID of the invoice");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdLabel)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Process, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Particular, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Particular, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Process, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParticularActionPerformed
        // TODO add your handling code here:
        cuadroMostrar.setText("");
        String Id = ID.getText();
        controller.read(Id, cuadroMostrar);
        ID.setText("");
    }//GEN-LAST:event_ParticularActionPerformed

    private void ProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessActionPerformed
        // TODO add your handling code here:
        cuadroMostrar.setText("");
        String Id = ID.getText();
        controller.update(Id);
        ID.setText("");
    }//GEN-LAST:event_ProcessActionPerformed

    private void PendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendientesActionPerformed
        // TODO add your handling code here:
        cuadroMostrar.setText("");
        controller.readPendings(cuadroMostrar);
    }//GEN-LAST:event_PendientesActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        // TODO add your handling code here:
        cuadroMostrar.setText("");
        controller.readProcessed(cuadroMostrar);
    }//GEN-LAST:event_ReportActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        cuadroMostrar.setText("");
        InicioView venO = new InicioView();
        venO.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JButton Particular;
    private javax.swing.JButton Pendientes;
    private javax.swing.JButton Process;
    private javax.swing.JButton Report;
    private javax.swing.JTextArea cuadroMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

class ImagenFondo5 extends JPanel {

    //Atributos
    private Image imagen;

    //Metodos
    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon(getClass().getResource("/Imagen/Modulo2.png")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
}
